#!/usr/bin/env bash

CONFIG=~/.cf/config.json

extract() {
  regex=$1
  position=${2:-1}

  if [[ ! -f "${CONFIG}" ]]; then
    echo "${CONFIG}" not found. Please configure 'cf' first.
    return
  fi
  i=1
  while read -r line; do
    if [[ $line =~ $regex ]]; then
      if [[ "${i}" = "${position}" ]]; then
        echo "${BASH_REMATCH[1]}"
        break
      else
        i=$((i+1))
      fi
    fi
  done < "${CONFIG}"
}

__cf_api_endpoint() {
  extract \"Target\":\ \"https?://\([^\"]+\)\"
}

__cf_user() {
  encoded=$(extract \"AccessToken\":\ \"bearer\ [^\.]+\.\([^\.]+\)\.[^\.]+\")
  case $((${#encoded} % 4)) in
  2)
    suffix='=='
    ;;
  3)
    suffix='='
    ;;
  esac
  decoded=$(openssl base64 -d -A <<< "${encoded}${suffix}")

  if [[ $decoded =~ \"email\":\"([^\"]+)\" ]]; then
    echo "${BASH_REMATCH[1]}"
  fi
}

__cf_org() {
  extract \"Name\":\ \"\([^\"]+\)\",
}

__cf_space() {
  extract \"Name\":\ \"\([^\"]+\)\", 2
}
